function du = cd6(ue,dx,periodic)
%
% Returns the 6th-order centered difference derivative of the function 
% defined in the array ue
% Usage is
% du = cd6(ue,dx,periodic)
% where 
%  dx        is the grid spacing (assumed uniform)
%  periodic  is a flag which is set to 1 to indicate periodic treatment of ghost values
%  ue        is the array to be differentiated 
%  du        is the array containing the finite difference approximation
%
  Ne=length(ue);
  du(4:Ne-3) =(45*(ue(5:Ne-2)-ue(3:Ne-4))...
               -9*(ue(6:Ne-1)-ue(2:Ne-5))...
               +  (ue(7:Ne  )-ue(1:Ne-6)))/(60*dx); % Centered 6th order
  if (periodic)
  du(3     ) =(45*(ue(4     )-ue(2     ))...
               -9*(ue(5     )-ue(1     ))...
               +  (ue(6     )-ue(Ne-1  )))/(60*dx); % Centered 6th order
  du(2     ) =(45*(ue(3     )-ue(1     ))...
               -9*(ue(4     )-ue(Ne-1  ))...
               +  (ue(5     )-ue(Ne-2  )))/(60*dx); % Centered 6th order
  du(1     ) =(45*(ue(2     )-ue(Ne-1  ))...
               -9*(ue(3     )-ue(Ne-2  ))...
               +  (ue(4     )-ue(Ne-3  )))/(60*dx); % Centered 6th order

  du(Ne-2) =  (45*(ue(Ne-1)-ue(Ne-3))...
               -9*(ue(Ne  )-ue(Ne-4))...
               +  (ue(2   )-ue(Ne-5)))/(60*dx); % Centered 6th order
  du(Ne-1) =  (45*(ue(Ne  )-ue(Ne-2))...
               -9*(ue(2   )-ue(Ne-3))...
               +  (ue(3   )-ue(Ne-4)))/(60*dx); % Centered 6th order
  du(Ne  ) =  (45*(ue(2   )-ue(Ne-1))...
               -9*(ue(3   )-ue(Ne-2))...
               +  (ue(4   )-ue(Ne-3)))/(60*dx); % Centered 6th order
  end
