function du = cd8(ue,dx,periodic)
%
% Returns the 8th-order centered difference derivative of the function 
% defined in the array ue
% Usage is
% du = cd8(ue,dx,periodic)
% where 
%  dx        is the grid spacing (assumed uniform)
%  ue        is the array to be differentiated 
%  periodic  is a flag to treat boundary ghost point periodically
%  du        is the array containing the finite difference approximation
%
  Ne=length(ue);

  du(5:Ne-4) =(672*(ue(6:Ne-3)-ue(4:Ne-5))...
              -168*(ue(7:Ne-2)-ue(3:Ne-6))...
              + 32*(ue(8:Ne-1)-ue(2:Ne-7))...
              -  3*(ue(9:Ne  )-ue(1:Ne-8)))/(840*dx); % Centered 8th order
  if (periodic == 1)
    du(4) =(672*(ue(5)-ue(3   ))...
           -168*(ue(6)-ue(2   ))...
           + 32*(ue(7)-ue(1   ))...
           -  3*(ue(8)-ue(Ne-1)))/(840*dx); % Centered 8th order
    du(3) =(672*(ue(4)-ue(2   ))...
           -168*(ue(5)-ue(1   ))...
           + 32*(ue(6)-ue(Ne-1))...
           -  3*(ue(7)-ue(Ne-2)))/(840*dx); % Centered 8th order
    du(2) =(672*(ue(3)-ue(1   ))...
           -168*(ue(4)-ue(Ne-1))...
           + 32*(ue(5)-ue(Ne-2))...
           -  3*(ue(6)-ue(Ne-3)))/(840*dx); % Centered 8th order
    du(1) =(672*(ue(2)-ue(Ne-1))...
           -168*(ue(3)-ue(Ne-2))...
           + 32*(ue(4)-ue(Ne-3))...
           -  3*(ue(5)-ue(Ne-4)))/(840*dx); % Centered 8th order
    du(Ne-3) =(672*(ue(Ne-2)-ue(Ne-4))...
              -168*(ue(Ne-1)-ue(Ne-5))...
              + 32*(ue(Ne  )-ue(Ne-6))...
              -  3*(ue(   2)-ue(Ne-7)))/(840*dx); % Centered 8th order
    du(Ne-2) =(672*(ue(Ne-1)-ue(Ne-3))...
              -168*(ue(Ne  )-ue(Ne-4))...
              + 32*(ue(   2)-ue(Ne-5))...
              -  3*(ue(   3)-ue(Ne-6)))/(840*dx); % Centered 8th order
    du(Ne-1) =(672*(ue(Ne  )-ue(Ne-2))...
              -168*(ue(   2)-ue(Ne-3))...
              + 32*(ue(   3)-ue(Ne-4))...
              -  3*(ue(   4)-ue(Ne-5)))/(840*dx); % Centered 8th order
    du(Ne  ) =(672*(ue(   2)-ue(Ne-1))...
              -168*(ue(   3)-ue(Ne-2))...
              + 32*(ue(   4)-ue(Ne-3))...
              -  3*(ue(   5)-ue(Ne-4)))/(840*dx); % Centered 8th order
  end
